// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.3.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

List<DiffElement> diff({required String text1, required String text2}) =>
    RustLib.instance.api.crateApiSimpleDiff(text1: text1, text2: text2);

class DiffElement {
  final String value;
  final DiffSign sign;

  const DiffElement({
    required this.value,
    required this.sign,
  });

  @override
  int get hashCode => value.hashCode ^ sign.hashCode;

  @override
  String toString() => "${sign.value} $value";

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DiffElement &&
          runtimeType == other.runtimeType &&
          value == other.value &&
          sign == other.sign;
}

enum DiffSign {
  delete('-'),
  insert('+'),
  equal(' ');

  final String value;
  const DiffSign(this.value);
}
